# -*- coding: utf-8 -*-
"""
Hujjatdagi maydon nomlari (LABELS) va botning savollari (PROMPTS) —
uz_latin / uz_cyrillic / ru uchun alohida.
"""

LABELS = {
    "uz_latin": {
        "doc_title": "MA'LUMOTNOMA",
        "birth_date": "Tug'ilgan yili:",
        "birth_place": "Tug'ilgan joyi:",
        "nationality": "Millati:",
        "education_level": "Ma'lumoti:",
        "education_detail": "Qachon, qaysi o'quv yurtini tugatgan:",
        "specialty": "Mutaxassisligi:",
        "academic_degree": "Ilmiy darajasi:",
        "academic_title": "Ilmiy unvoni:",
        "foreign_lang": "Qaysi chet tillari beriladi:",
        "military_title": "Harbiy (mahsus) unvoni:",
        "state_awards": "Davlat mukofotlari bilan taqdirlanganmi (qanday):",
        "work_history_heading": "MEHNAT FAOLIYATI:",
        "rel_title_tpl": "{name}ning yaqin qarindoshlari to'g'risida\nMA'LUMOT",
        "rel_col_relation": "Qarindoshligi",
        "rel_col_name": "Familiyasi, ismi va otasining ismi",
        "rel_col_birth": "Tug'ilgan yili va joyi",
        "rel_col_work": "Ish joyi va lavozimi",
        "rel_col_address": "Turar joyi",
    },
    "uz_cyrillic": {
        "doc_title": "МАЪЛУМОТНОМА",
        "birth_date": "Туғилган йили:",
        "birth_place": "Туғилган жойи:",
        "nationality": "Миллати:",
        "education_level": "Маълумоти:",
        "education_detail": "Қачон, қайси ўқув юртини тугатган:",
        "specialty": "Мутахассислиги:",
        "academic_degree": "Илмий даражаси:",
        "academic_title": "Илмий унвони:",
        "foreign_lang": "Қайси чет тиллари билади:",
        "military_title": "Ҳарбий (махсус) унвони:",
        "state_awards": "Давлат мукофотлари билан тақдирланганми (қандай):",
        "work_history_heading": "МЕҲНАТ ФАОЛИЯТИ:",
        "rel_title_tpl": "{name}нинг яқин қариндошлари тўғрисида\nМАЪЛУМОТ",
        "rel_col_relation": "Қариндошлиги",
        "rel_col_name": "Фамилияси, исми ва отасининг исми",
        "rel_col_birth": "Туғилган йили ва жойи",
        "rel_col_work": "Иш жойи ва лавозими",
        "rel_col_address": "Турар жойи",
    },
    "ru": {
        "doc_title": "СПРАВКА",
        "birth_date": "Год рождения:",
        "birth_place": "Место рождения:",
        "nationality": "Национальность:",
        "education_level": "Образование:",
        "education_detail": "Когда и какое учебное заведение окончил(а):",
        "specialty": "Специальность:",
        "academic_degree": "Учёная степень:",
        "academic_title": "Учёное звание:",
        "foreign_lang": "Какими иностранными языками владеет:",
        "military_title": "Воинское (специальное) звание:",
        "state_awards": "Награждён(а) ли государственными наградами (какими):",
        "work_history_heading": "ТРУДОВАЯ ДЕЯТЕЛЬНОСТЬ:",
        "rel_title_tpl": "СВЕДЕНИЯ\nо близких родственниках {name}",
        "rel_col_relation": "Родство",
        "rel_col_name": "Фамилия, имя и отчество",
        "rel_col_birth": "Год и место рождения",
        "rel_col_work": "Место работы и должность",
        "rel_col_address": "Место жительства",
    },
}

PROMPTS = {
    "uz_latin": {
        "full_name": "F.I.Sh. (to'liq, masalan: Husenov Jahongir Qo'shmurod o'g'li):",
        "photo_prompt": "3x4 rasmni yuboring (Telegram orqali oddiy foto sifatida):",
        "birth_date": "Tug'ilgan yili (sana bilan, masalan: 08.11.2001 y.):",
        "birth_place": "Tug'ilgan joyi (masalan: Buxoro viloyati, Shofirkon tumani):",
        "nationality": "Millatingiz:",
        "education_level": "Ma'lumotingiz (masalan: Oliy / Tugallanmagan oliy / O'rta maxsus):",
        "education_detail": "Qachon, qaysi o'quv yurtini tugatgan (yoki hozir qaysi kursda o'qiyotgani):",
        "specialty": "Mutaxassisligingiz:",
        "academic_degree": "Ilmiy darajasi (bo'lmasa \"Yo'q\" deb yozing):",
        "academic_title": "Ilmiy unvoni (bo'lmasa \"Yo'q\" deb yozing):",
        "foreign_lang": "Qaysi chet tillarini bilasiz (bo'lmasa \"-\" deb yozing):",
        "military_title": "Harbiy (maxsus) unvoningiz (bo'lmasa \"Yo'q\" deb yozing):",
        "state_awards": "Davlat mukofotlari bilan taqdirlanganmisiz? (qanday, yoki \"Taqdirlanmagan\"):",
        "work_years": "Mehnat faoliyati — davri (masalan: 2019-2023-yillar):",
        "work_position": "Shu davrdagi ish/lavozim nomini yozing:",
        "work_more": "Yana bitta mehnat faoliyati bandini qo'shamizmi?",
        "ask_relatives": "Yaqin qarindoshlari to'g'risida ma'lumot hujjati ham kerakmi?",
        "rel_relation": "Qarindoshlik turini tanlang:",
        "rel_name": "Uning F.I.Sh. (to'liq):",
        "rel_birth": "Tug'ilgan yili va joyi:",
        "rel_work": "Ish joyi va lavozimi:",
        "rel_address": "Turar joyi (manzili):",
