from aiogram.fsm.state import State, StatesGroup


class ObyektivkaForm(StatesGroup):
    language = State()
    script = State()
    photo = State()
    full_name = State()
    position_since = State()
    current_position = State()
    birth_date = State()
    birth_place = State()
    nationality = State()
    party_affiliation = State()
    education_level = State()
    graduated_from = State()
    specialty = State()
    academic_degree = State()
    academic_title = State()
    foreign_languages = State()
    military_title = State()
    state_awards = State()
    departmental_awards = State()
    elected_member = State()
    work_entry = State()
    work_entry_more = State()

    # Yaqin qarindoshlar haqida (2-sahifa jadvali uchun)
    relative_relation = State()
    relative_name = State()
    relative_birth = State()
    relative_job = State()
    relative_address = State()
    relative_more = State()
